#!/system/bin/sh
#
# AK Tuning
# @anarkia1976
#

# initialize ak
echo "[ak kernel] initialize boot script" | tee /dev/kmsg

# disable debugging on some modules
echo "0" > /sys/module/kernel/parameters/initcall_debug;
echo "0" > /sys/module/alarm/parameters/debug_mask;
echo "0" > /sys/module/alarm_dev/parameters/debug_mask;
echo "0" > /sys/module/binder/parameters/debug_mask;
echo "0" > /sys/module/xt_qtaguid/parameters/debug_mask;
echo "[ak kernel] disable debug mask" | tee /dev/kmsg

# tuning interactive governor
#echo "70" > /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
#echo "1728000" > /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
#echo "1" > /sys/devices/system/cpu/cpufreq/interactive/io_is_busy
#echo "40000" > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
#echo "[ak kernel] tuning interactive governor" | tee /dev/kmsg

# set min/max freqs after boot
minfreq="300000"
echo "$minfreq" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo "$minfreq" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
echo "$minfreq" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq
echo "$minfreq" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq

maxfreq="2457600"
echo "$maxfreq" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo "$maxfreq" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
echo "$maxfreq" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
echo "$maxfreq" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq
echo "[ak kernel] set min-max freqs after boot" | tee /dev/kmsg
